spring.application.name=streakly-habit-tracker

server.port=8080

# Persistent local database file inside the project.
spring.datasource.url=jdbc:h2:file:./data/streaklydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Keep API responses clean.
spring.jackson.serialization.write-dates-as-timestamps=false

# H2 console for local development.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
